/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components': RouteRecordInfo<'/components', '/components', Record<never, never>, Record<never, never>>,
    '/contracts/': RouteRecordInfo<'/contracts/', '/contracts', Record<never, never>, Record<never, never>>,
    '/contracts/[id]': RouteRecordInfo<'/contracts/[id]', '/contracts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, '/contracts/[id]/' | '/contracts/[id]/edit/[[tab]]'>,
    '/contracts/[id]/': RouteRecordInfo<'/contracts/[id]/', '/contracts/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/contracts/[id]/edit/[[tab]]': RouteRecordInfo<'/contracts/[id]/edit/[[tab]]', '/contracts/:id/edit/:tab?', { id: ParamValue<true>, tab?: ParamValueZeroOrOne<true> }, { id: ParamValue<false>, tab?: ParamValueZeroOrOne<false> }>,
    '/contracts/new/[[tab]]': RouteRecordInfo<'/contracts/new/[[tab]]', '/contracts/new/:tab?', { tab?: ParamValueZeroOrOne<true> }, { tab?: ParamValueZeroOrOne<false> }>,
    '/locations/': RouteRecordInfo<'/locations/', '/locations', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/components.vue': {
      routes: '/components'
      views: never
    }
    'src/pages/contracts/index.vue': {
      routes: '/contracts/'
      views: never
    }
    'src/pages/contracts/[id].vue': {
      routes: '/contracts/[id]' | '/contracts/[id]/' | '/contracts/[id]/edit/[[tab]]' | '/contracts/[id]/edit'
      views: 'default'
    }
    'src/pages/contracts/[id]/index.vue': {
      routes: '/contracts/[id]/'
      views: never
    }
    'src/pages/contracts/[id]/edit/[[tab]].vue': {
      routes: '/contracts/[id]/edit/[[tab]]'
      views: never
    }
    'src/pages/contracts/new/[[tab]].vue': {
      routes: '/contracts/new/[[tab]]'
      views: never
    }
    'src/pages/locations/index.vue': {
      routes: '/locations/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
