/**
 * Mock location data for development
 */

import type { Location, LocationListing } from '../model/location'

// Generate a unique ID
export function generateId(): string {
  return Math.random().toString(36).slice(2, 11)
}

// Convert full location to listing format
export function locationToListing(location: Location): LocationListing {
  return {
    id: location.id,
    identifier: location.identifier,
    name: location.name,
    city: location.city,
    state: location.state,
    type: location.type,
    active: location.active,
  }
}

// Mock locations data
export const mockLocations: Location[] = [
  {
    id: 'loc-001',
    identifier: 'FH001',
    name: 'Evergreen Memorial Funeral Home',
    type: 'funeral',
    active: true,
    address1: '1234 Oak Street',
    address2: 'Suite 100',
    city: 'Springfield',
    state: 'IL',
    postalCode: '62701',
    country: 'USA',
    phone: '(217) 555-0100',
    email: 'info@evergreenmemorial.com',
    website: 'https://evergreenmemorial.com',
    mailingSameAsPhysical: true,
    mailingAddress1: '',
    mailingAddress2: '',
    mailingCity: '',
    mailingState: '',
    mailingPostalCode: '',
    mailingCountry: '',
    licenses: [
      {
        id: 'lic-001',
        licenseNumber: 'FH-2024-001234',
        licenseType: 'establishment',
      },
      {
        id: 'lic-002',
        licenseNumber: 'INS-2024-005678',
        licenseType: 'insurance',
      },
    ],
    taxId: '12-3456789',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-20T14:30:00Z',
  },
  {
    id: 'loc-002',
    identifier: 'CEM001',
    name: 'Peaceful Valley Cemetery',
    type: 'cemetery',
    active: true,
    address1: '5678 Valley Road',
    address2: '',
    city: 'Riverside',
    state: 'CA',
    postalCode: '92501',
    country: 'USA',
    phone: '(951) 555-0200',
    email: 'contact@peacefulvalley.com',
    website: 'https://peacefulvalleycemetery.com',
    mailingSameAsPhysical: false,
    mailingAddress1: 'PO Box 1234',
    mailingAddress2: '',
    mailingCity: 'Riverside',
    mailingState: 'CA',
    mailingPostalCode: '92502',
    mailingCountry: 'USA',
    licenses: [
      {
        id: 'lic-003',
        licenseNumber: 'CEM-2024-009876',
        licenseType: 'establishment',
      },
    ],
    taxId: '98-7654321',
    createdAt: '2023-06-01T08:00:00Z',
    updatedAt: '2024-03-15T11:45:00Z',
  },
  {
    id: 'loc-003',
    identifier: 'FH002',
    name: 'Sunrise Chapel & Crematory',
    type: 'funeral',
    active: true,
    address1: '789 Sunrise Boulevard',
    address2: '',
    city: 'Phoenix',
    state: 'AZ',
    postalCode: '85001',
    country: 'USA',
    phone: '(602) 555-0300',
    email: 'services@sunrisechapel.com',
    website: 'https://sunrisechapel.com',
    mailingSameAsPhysical: true,
    mailingAddress1: '',
    mailingAddress2: '',
    mailingCity: '',
    mailingState: '',
    mailingPostalCode: '',
    mailingCountry: '',
    licenses: [
      {
        id: 'lic-004',
        licenseNumber: 'FH-2024-002345',
        licenseType: 'establishment',
      },
      {
        id: 'lic-005',
        licenseNumber: 'TR-2024-003456',
        licenseType: 'trust',
      },
    ],
    taxId: '45-6789012',
    createdAt: '2024-02-20T09:30:00Z',
    updatedAt: '2024-07-10T16:20:00Z',
  },
  {
    id: 'loc-004',
    identifier: 'CORP01',
    name: 'Memorial Services Corporate Office',
    type: 'corporate',
    active: true,
    address1: '100 Corporate Plaza',
    address2: '15th Floor',
    city: 'Chicago',
    state: 'IL',
    postalCode: '60601',
    country: 'USA',
    phone: '(312) 555-0400',
    email: 'corporate@memorialservices.com',
    website: 'https://memorialservicescorp.com',
    mailingSameAsPhysical: true,
    mailingAddress1: '',
    mailingAddress2: '',
    mailingCity: '',
    mailingState: '',
    mailingPostalCode: '',
    mailingCountry: '',
    licenses: [],
    taxId: '56-7890123',
    createdAt: '2022-01-01T00:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'loc-005',
    identifier: 'CEM002',
    name: 'Garden of Memories',
    type: 'cemetery',
    active: true,
    address1: '2000 Memorial Drive',
    address2: '',
    city: 'Austin',
    state: 'TX',
    postalCode: '78701',
    country: 'USA',
    phone: '(512) 555-0500',
    email: 'info@gardenofmemories.com',
    website: '',
    mailingSameAsPhysical: true,
    mailingAddress1: '',
    mailingAddress2: '',
    mailingCity: '',
    mailingState: '',
    mailingPostalCode: '',
    mailingCountry: '',
    licenses: [
      {
        id: 'lic-006',
        licenseNumber: 'CEM-2024-004567',
        licenseType: 'establishment',
      },
    ],
    taxId: '67-8901234',
    createdAt: '2023-09-15T14:00:00Z',
    updatedAt: '2024-05-22T09:15:00Z',
  },
  {
    id: 'loc-006',
    identifier: 'FH003',
    name: 'Heritage Funeral Home',
    type: 'funeral',
    active: false,
    address1: '456 Heritage Lane',
    address2: '',
    city: 'Denver',
    state: 'CO',
    postalCode: '80202',
    country: 'USA',
    phone: '(303) 555-0600',
    email: 'heritage@funeral.com',
    website: 'https://heritagefuneralhome.com',
    mailingSameAsPhysical: true,
    mailingAddress1: '',
    mailingAddress2: '',
    mailingCity: '',
    mailingState: '',
    mailingPostalCode: '',
    mailingCountry: '',
    licenses: [
      {
        id: 'lic-007',
        licenseNumber: 'FH-2023-005678',
        licenseType: 'establishment',
      },
    ],
    taxId: '78-9012345',
    createdAt: '2020-03-10T12:00:00Z',
    updatedAt: '2024-08-01T08:00:00Z',
  },
]
